name: sce_reg
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - cudatoolkit=11.3
  - cudnn=8.2
  - python=3.10
  - matplotlib
  - nibabel
  - pandas
  - pyyaml
  - scipy
  - simpleitk
  - pip
  - pip:
    - tensorflow==2.9.0